name: vapelurr_store
description: A vape store app using Flutter + Supabase
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.2.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # --------------------
  # STATE MANAGEMENT
  # --------------------
  provider: ^6.0.5

  # --------------------
  # SUPABASE
  # --------------------
  supabase_flutter: ^2.5.0
  supabase: ^2.0.8

  # --------------------
  # UI & UTILITIES
  # --------------------
  cupertino_icons: ^1.0.6
  http: ^1.1.0
  shared_preferences: ^2.2.2
  intl: ^0.19.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

  # --------------------------
  # Locatioan & MAP
  #---------------------------

  location: ^5.0.0
  geocoding: ^2.1.0
  flutter_map: ^6.1.0
  latlong2: ^0.9.0

  geolocator: ^10.1.1 

flutter:
  uses-material-design: true

